name = input('what is your name ?')
print('your name is ' + name)
color = input('what is your favourite color?')
print( name + ' likes ' + color)
my_name = "Madhurjya Saha"
print(len(my_name))
print(my_name[9:-1])
print(my_name.upper())
print(my_name.replace("M" , "S"))
print(my_name.title())
print(my_name.find("s"))
print(bool(""))
print('hello world')